export const elements = {
  canvas: document.getElementById('myCanvas'),
  gradientOptions: document.getElementById('gradients-options'),
  configToggle: document.getElementById('config-toggle'),
  colorToggle: document.getElementById('color-toggle'),
  inputOne: document.getElementById('0'),
  inputTwo: document.getElementById('1'),
  addGradient: document.getElementById('add-gradient'),
  removeGradient: document.getElementById('remove-gradient'),
  downloadBtn: document.getElementById('btn-download'),
  cPicker: document.getElementById('colorPicker'),
  selectMode: document.getElementById('select-mode'),
  menu: document.getElementsByClassName('menu')[0],
  flex: document.getElementsByClassName('flex'),
  extensionOptions: document.getElementsByClassName('extension'),
  solidOptions: document.getElementById('solid-options'),
  gradientSelector: document.getElementById('gradientSelector'),
  solidSelector: document.getElementById('solidSelector'),
}
